### ISSUE TITLE
Use a PHPUnit config file

### ISSUE THREAD

**Issue by potherca** [Ariadne-CMS/arc-base#13]
Instead of the current mechanism left over from using SimpleTest, I would suggest creating a config `phpunit.xml.dist` file to use with PHPUnit. An example of how this would work can be found in [this commit][1].

If the need for using a constant to define the `TESTDIR` can be removed the `bootstrap` entry in the XML could be pointed directly to the vendor autoloader without negating this to the bootstrap.

One of the benefits would be that simply running `phpunit` would be enought to run all the tests, no separate bootstrap per repo needed.

In the example I've also taken the liberty of adding some suggestions of output to log to stdout to be easily available in the build (or when running the tests locally). I will follow up on this in a later pull-request.

As a side-note: Good work on the `contributing.md` nice to see that little link in the PR-UI on github :smile: 

[1]: https://github.com/potherca/arc-arc/commit/590e50e4a41423519629b6294224433a500026e9

**Comment by poef** [comment]
I think this has all been done now
