### ISSUE TITLE
The call to Prototype::getLocalProperties() has too many arguments starting with $this.

### ISSUE THREAD

**Issue by mjrider** [Ariadne-CMS/arc-base#18]
see https://scrutinizer-ci.com/g/Ariadne-CMS/arc-base/inspections/5038914a-2d64-48c0-90b1-9fdafad04935/issues/files/src/lambda/Prototype.php?status=fixed&orderField=path&order=asc#inspectioncomment-892144760

**Comment by poef** [comment]
Prototype is now in a seperate component repository, and completely rewritten. This is no longer an issue.
